spring:
    h2:
        console:
            enabled: false
            path: /h2-console
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
server:
    tomcat:
        max-swallow-size: -1